### ISSUE TITLE
Expense 관련 뷰에서 -1 문제를 해결합니다.

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#145]
## 👀 개요
- 지금은 금액 정보를 입력하지 않고 저장하면 .payAmount 부분에 -1이 저장됩니다.
- 이때 -1이 금액으로 인식되는 문제가 있습니다.
- 이것을 지출 목록에는 표시하되, 합계에는 포함이 되지 않아야 합니다.
- 지출 목록에서 보여줄 때, 금액을 어떻게 표시해야 할지 고민해야 합니다. (-, ?, 미정 등)

## 📝 TODO
- [x] payAmount의 값이 -1일 때, 합계에 포함되지 않게 하기
- [x] payAmount의 값이 -1일 때, 다른 문자로 보여주기

**Comment by oliver-or-not** [comment]
파이팅~~~!~!!~!
