### ISSUE TITLE
RecordViewModel 오류 확인해주세요.

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#169]
## 👀 개요
- 방금 @unboxing96 의 브랜치를 merge하고 pull 받은 dev 브랜치에서 오류가 나타납니다.
<img width="238" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/assets/93391058/92b15bed-c16e-4deb-a2d9-3f44292063b6">

## 📝 TODO
- [x] 오류 해결하기

**Comment by oliver-or-not** [comment]
제가 삭제한 코드인데 페페의 코드와 병합되면서 되살아났습니다.
```
chosenTravel = findCurrentTravel()
```

```
    func setChosenTravel(as travel: Travel) {
        chosenTravel = travel
    }
```
위의 코드를 지우면 실행될겁니다!

**Comment by GYURI-PARK** [comment]
> 제가 삭제한 코드인데 페페의 코드와 병합되면서 되살아났습니다.
> 
> ```
> chosenTravel = findCurrentTravel()
> ```
> 
>  ```
>     func setChosenTravel(as travel: Travel) {
>         chosenTravel = travel
>     }
> ```
> 
> 위의 코드를 지우면 실행될겁니다!

페페가 쓴다고 해서 제가 머지하면서 남겨두었던 거 같은데 삭제해도될까요..??

**Comment by oliver-or-not** [comment]
저 부분은 안쓸걸요..? @unboxing96

**Comment by unboxing96** [comment]
> > 제가 삭제한 코드인데 페페의 코드와 병합되면서 되살아났습니다.
> > ```
> > chosenTravel = findCurrentTravel()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> >    func setChosenTravel(as travel: Travel) {
> >        chosenTravel = travel
> >    }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 위의 코드를 지우면 실행될겁니다!
> 
> 페페가 쓴다고 해서 제가 머지하면서 남겨두었던 거 같은데 삭제해도될까요..??

![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/assets/102353544/67adeb96-e278-4179-adad-ea6f163b164a)

제가 전달을 명확히 하지 않았네요. 
도리스가 캡처한 사진에서 chosenTravel = findCurrentTravel() 아래 줄부터는 제가 사용하는 코드입니다.
