### ISSUE TITLE
❗️HELP❗️Merge 이후에 Xcode 실행이 안됩니다,

### ISSUE THREAD

**Issue by GYURI-PARK** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#23]
## 👀 개요

<img width="981" alt="Pasted Graphic 1" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/assets/93391058/c27614c6-5e50-4993-8af7-ef9caeac665d">

Core Data에서 다음과 같은 오류가 발생합니다.

![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/assets/93391058/74db0ea1-a5a8-4c7c-8f34-ce347fe852aa)

## 📝 TODO
- [x] 오류해결 후 재 merge.

**Comment by oliver-or-not** [comment]
제가 해결해볼게요~

**Comment by oliver-or-not** [comment]
코어 데이터 엔터티의 애트리뷰트 타입을 바꾸어, 기존 앱에 저장되어 있던 데이터와 호환이 되지 않아 발생하는 에러라고 합니다.
비슷한 에러에 관한 링크: https://stackoverflow.com/questions/34601027/failed-to-initialize-the-applications-saved-data

저는 코드를 수정하지 않고 시뮬레이터에서 앱을 삭제하고 다시 빌드하니 에러가 사라졌습니다.

**Comment by unboxing96** [comment]
저는 아래 링크를 보고 preview crashed 문제도 해결되었어요.
핵심은 스크린샷에 요약되어 있어요.

<img width="553" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team11-UMM/assets/102353544/e0063d50-9bf5-406c-91be-56ed8765fb0c">

링크: https://www.reddit.com/r/SwiftUI/comments/h0fyck/swiftui_coredata_preview_canvas_asks_for_migration/
