### ISSUE TITLE
최초 출시 후 개선할 사항

### ISSUE THREAD

**Issue by oliver-or-not** [DeveloperAcademy-POSTECH/MacC-Team11-UMM#264]
## 👀 개요
- 최초 출시(1.0.0) 후 발견된 개선할 사항들을 기록하는 이슈입니다.
- 별도의 이슈로 분리한 것은 여기서 삭제해주세요~~!

#### 심각한 버그
- [ ] 앱이 실행되지 않는 문제(by Flynn)

#### 덜 심각한 버그
- [ ] 여행 선택 모달에서 임시 기록에 이중의 이름이 보여지는 문제
- [ ] TodayExpenseView에서 금액 합에 가끔 음수(* -100)가 나오는 문제

#### 개선할 점 - 스토어
- [x] 스토어 표기에서 저작권 기호 빼기

#### 개선할 점 - UI
- [ ] 글자 크기와 텍스트 뷰 크기(한 줄 텍스트, 여러 줄 텍스트 가로 세로) 피그마에 정확하게 맞추기
- [ ] 텍스트 뷰 다이나믹 사이즈 테스트하고 뷰 조절하기
- [ ] 다양한 기기 크기 테스트하고 뷰 조절하기
- [ ] 여행 생성하기 -> 달력 페이지로 바로 갈까?
- [ ] 녹음 버튼 안정성... 이대로 괜찮은가?

#### 개선할 점 - 구조
- [ ] 여행, 지출 등을 코어 데이터에서 fetch하고 즉시 필터하는 코드는 precidate로 대체하기
- [ ] 워치와의 연동을 위해 무언가 하기
- [ ] UIScreen.main 다른 코드로 대체하기

#### 추가 기능
- [ ] 워치

**Comment by unboxing96** [comment]
최고의 CTO.

**Comment by oliver-or-not** [comment]
스프레드시트로 전체 목록을 관리하고 이 이슈는 닫습니다.
